sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install pipenv --upgrade
- pipenv install --dev --skip-lock
script:
- pipenv run py.test --verbose --cov-report term --cov-report xml --junitxml=report.xml
  --cov=doclink tests
after_success:
- codecov
deploy:
  provider: pypi
  user: yufu_luo
  password:
    secure: QQp3LH4XFLGUciFd8HtkgU+8bMi+LLfzUp6WCr8lwqyqLqxzj1tFWmdHLVEq9+VXy+YSv3e4ZT1Mt0aQuAIcenVef6pdiWr0VcfPIeepqgJXDJp4Dvu6ae33e9YoQi/9nkzedoqg720TM2IZk7n6lwXFVB1qeDoWUyqHPHmhSXz8sC7vvZ7PIIJh287+sQqn4RYICcfIAYrpnSbNqvaZdHWbC7c7zRsCokEJtKs1CqcbayWZkWNhPcQyeWNhN2p1yKeLAkokGx20sEvd8devkhOEbacL9X2YRObLFrRg/lb8llBc4HAky8Y6SMDm2yiO69wT1ibpHhOkMj1/LX5VgY8e+hQmXm/AvsntUyfhWG+X5wtQuY0AU9iTfRXpxq8NHIQTCepnH08msBoDml9eT8puWZbRFOteEL6t2PTCl/W3qYOgqQwpDB/tSaswXMSZvxk1mDc/OjPUP183ZzMwn4W/2I5EUrIfCNdXZhNe+g3wK4b5afnhCzGL4Bjmq/g69QgVZHLczEPX8JVi9LiP8aYOHQrXLtoGshDY4hPbFjLJEN8SpGHiIits3IeU7ZhduViN/tpOIj+jpJ1TNCpeKtzHzNE2vXoUlz7ZXnbPl7InOlhSep6UzRDG7PhTdgHtb3PGF0WUxTSotIaR/vCWiSexF5EgmCmUtbIpgbPmFjE=
  on:
    tags: true
    python: '3.6'
  distributions: "sdist bdist_wheel"
