sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install pipenv --upgrade
- pipenv install --dev --skip-lock
script:
- pipenv run py.test --verbose --cov-report term --cov-report xml --junitxml=report.xml
  --cov=doclink tests
after_success:
- codecov
deploy:
  provider: pypi
  user: yufu_luo
  password:
    secure: oVJi2mM2BGhgBALSKfoeUH1sDYMp9ZYZmVNaT4gIfzaP/F3QbHh931GxDu4+az121IDGaE+TlYfEbJSvaU1B0TyEQ7gITNGqqgG2JkAFBr1cQjADcoCd8j6hF53/r/7+te3gu8ew5QXOSUDRirYipHn2I/MiMvGP8uaWrtzHRgUYVae0DCd7uWRPO95tD0mxh9hwr0JoS/G4l9tj/zfznETJj/1Zw4Kg/YJn2u87j8QMLX9+xyQCXmPn50KUArjB2l+Lp7f4+L4B+TykzTmcXiRaxXMi+UP9sLTXchspGY3jib2MoBU/uxwQchh0kH8ZlNVgpBGOUO2xwAm83MAych01+92tzNcTBwjarwgG6t1K13zwyc4pTp/iJMXSSU/b/FH0Bl83tvBbhLfq6fBIbJQsN8wZgnxKuS5z/l7p//LYGLPzDodvid+F+eAVoAyIlGShFOWge5DuW9ZqFhlvZazEQOsUTg8Jx09wcnGANyLaUhBeavxEWu/5WIgVjnDSIFC9yRRAqKXtE6eFf00CdELl6oKceI0BoBUjG1+3x/h5ZkpDWirF54Dd/pS3aFT9GVOnCRLOtmCk8+0YpoSulVvDF9wgx7RUZDKPSWiVW3ZHkPsMAg4ECoM3V1VRunm9ngZ56Kl4EbP4Ct+sw08XfWAK7ZjJTdvuDImjp6+iKRg=
  on:
    tags: true
    python: '3.6'
  distributions: sdist bdist_wheel
