init:
    pip install pipenv --upgrade
    pipenv install --dev --skip-lock
test:
    detox
ci:
    pipenv run py.test -n 4 --boxed --junitxml=report.xml
coverage:
    pipenv run py.test --verbose --cov-report term --cov-report xml --cov=doclink tests
publish:
    pip install 'twine>=1.5.0'
    python setup.py sdist bdist_wheel
    twine upload dist/*
    rm -fr build dist .egg requests.egg-info
